server:
  port: 8082

spring:
  application:
    name: booking-service

  rabbitmq:
    host: rabbitmq

  datasource:
    url: jdbc:mysql://mysql-db:3306/bookingdb?createDatabaseIfNotExist=true
    username: root
    password: 2005
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/