server:
  port: 8083 # <-- Cổng mới

spring:
  application:
    name: fleet-service # <-- Tên mới

  rabbitmq:
    host: rabbitmq
  
  datasource:
    url: jdbc:mysql://mysql-db:3306/fleetdb?createDatabaseIfNotExist=true # <-- DB mới
    username: root
    password: 2005
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/